In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import os, os.path 
import numpy 
import pickle
from glob import glob
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable 
import pandas as pd
from scipy import signal
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import random
#import seaborn as sns
"""
    number of trajectories in each city
    # austin --  train: 43041 test: 6325 
    # miami -- train: 55029 test:7971
    # pittsburgh -- train: 43544 test: 6361
    # dearborn -- train: 24465 test: 3671
    # washington-dc -- train: 25744 test: 3829
    # palo-alto -- train:  11993 test:1686

    trajectories sampled at 10HZ rate, input 5 seconds, output 6 seconds
    
"""

'\n    number of trajectories in each city\n    # austin --  train: 43041 test: 6325 \n    # miami -- train: 55029 test:7971\n    # pittsburgh -- train: 43544 test: 6361\n    # dearborn -- train: 24465 test: 3671\n    # washington-dc -- train: 25744 test: 3829\n    # palo-alto -- train:  11993 test:1686\n\n    trajectories sampled at 10HZ rate, input 5 seconds, output 6 seconds\n    \n'

In [2]:
# clean memory
import gc

gc.collect()

torch.cuda.empty_cache()

In [3]:
print(torch.cuda.get_device_name())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

GeForce RTX 2060 SUPER


In [4]:
from glob import glob
import pickle
import numpy as np

### Change to requried path to access data locally, too big too push all data into github
#ROOT_PATH = "C:/Users/Administrator/cse151b-spring2022/argo2/"
ROOT_PATH = "D:/School/cse151B/argo2/"

cities = ["austin", "miami", "pittsburgh", "dearborn", "washington-dc", "palo-alto"]
splits = ["train", "test"]

def get_city_trajectories(city="palo-alto", split="train", normalized=False):
    f_in = ROOT_PATH + split + "/" + city + "_inputs"
    inputs = pickle.load(open(f_in, "rb"))
    inputs = np.asarray(inputs)
    
    outputs = None
    
    if split=="train":
        f_out = ROOT_PATH + split + "/" + city + "_outputs"
        outputs = pickle.load(open(f_out, "rb"))
        outputs = np.asarray(outputs)

        return torch.from_numpy(inputs).float(), torch.from_numpy(outputs).long()

    if split=="test":
    
        return torch.from_numpy(inputs).float(), torch.from_numpy(np.array([]))

    

class ArgoverseDataset(Dataset):
    """Dataset class for Argoverse"""
    def __init__(self, city: str, split:str, transform=None, device='cpu'):
        super(ArgoverseDataset, self).__init__()
        self.transform = transform
        self.split = split
        self.inputs, self.outputs = get_city_trajectories(city=city, split=split, normalized=False)
        self.inputs = self.inputs.to(device)
        self.outputs = self.outputs.to(device)
    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):

        if self.split == 'train':
            data = (self.inputs[idx], self.outputs[idx])
        if self.split == 'test':
            data = self.inputs[idx]
            
        if self.transform:
            data = self.transform(data)

        return data

# intialize a dataset
city = 'palo-alto' 
split = 'train'
#train_dataset  = ArgoverseDataset(city = city, split = split, device=device)

In [5]:
#len(train_dataset) # current X is 50 in len and Y is 60 in len

In [6]:
#type(train_dataset)

### Data Preprocessing

In [7]:
# wrapper function to select proportion of a cities random examples w/o replacement from each city and put all data into one list
# purpose: whole dataset is too big and might be redundant
def randomCitySampler(prop):
    cities = ["austin", "miami", "pittsburgh", "dearborn", "washington-dc","palo-alto"]

    samples = []
    for c in cities:
        # get city data
        temp_dataset = ArgoverseDataset(city = c, split = "train", device=device)

        numProp = int(len(temp_dataset) * prop)

        # get N number of random indicies
        ind = random.sample(range(0, len(temp_dataset)), numProp)
        #print(ind)
        # push all data indicies into samples list
        for i in ind: 
            samples.append(temp_dataset[i])
    return samples


In [8]:
### constants for generating Dataset
proportionOfEntireData = 0.5
seqLen = 40
stepSize = 3
batch_sz = 64  # batch size 

In [9]:
# create train dataset, with proportion to actual amount data
sampleTest = randomCitySampler(proportionOfEntireData)
len(sampleTest)

101906

In [10]:
# generate sequences of length seqLength and specific step size
def sequenceGenerator(data, seqLen=40, stepSize=5):
    newData = []
    for d in data:
        # concat X and Y together
        temp = torch.cat([d[0],d[1]])
        # make X of length SeqLen and Y is next x,y coordinate pair
        for i in range(0,len(temp)-seqLen, stepSize):
            x = temp[i:i + seqLen]
            #flatX = Variable(torch.tensor([item for sublist in x for item in sublist])).to(device)
            flatX = torch.flatten(Variable(torch.tensor(x)).to(device))
            y = temp[i+seqLen]
            newData.append((flatX,y))
            
        
    return newData

In [11]:
# generate sequences
train_seq_data = sequenceGenerator(sampleTest,seqLen, stepSize)
len(train_seq_data)

<ipython-input-10-8e56f7b34fb3>:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  flatX = torch.flatten(Variable(torch.tensor(x)).to(device))


2445744

In [12]:
# should be a vector of size (80,2) for each example
train_seq_data[0], len(train_seq_data[0][0])

((tensor([ -87.9163, -322.9986,  -88.1431, -323.0446,  -88.4229, -323.1046,
           -88.7523, -323.1785,  -89.1441, -323.2702,  -89.5648, -323.3791,
           -89.9902, -323.5018,  -90.4510, -323.6474,  -90.9286, -323.8175,
           -91.3744, -323.9922,  -91.7776, -324.1633,  -92.1688, -324.3469,
           -92.5615, -324.5505,  -92.9547, -324.7736,  -93.3449, -325.0163,
           -93.7345, -325.2782,  -94.1237, -325.5560,  -94.5112, -325.8491,
           -94.8992, -326.1587,  -95.2867, -326.4835,  -95.6759, -326.8234,
           -96.0662, -327.1759,  -96.4612, -327.5439,  -96.8337, -327.9260,
           -97.1968, -328.3221,  -97.5762, -328.7369,  -97.9351, -329.1604,
           -98.2598, -329.5797,  -98.5809, -330.0077,  -98.9108, -330.4610,
           -99.2353, -330.9353,  -99.5548, -331.4230,  -99.8644, -331.9220,
          -100.1664, -332.4342, -100.4591, -332.9608, -100.7423, -333.5009,
          -101.0202, -334.0549, -101.2939, -334.6228, -101.5649, -335.2033,
          -1

In [13]:
# create loader
train_loader = DataLoader(train_seq_data,batch_size=batch_sz)

In [14]:
# check shape is correct
train_features, train_labels = next(iter(train_loader))
len(train_features[0]), train_labels[0]
# shape is correct

(80, tensor([-102.1050, -336.4034], device='cuda:0'))

### LSTM

In [15]:
# model parameters
#num_epochs = 60
learning_rate = 0.0001

input_size = seqLen*2 #number of features
hidden_size = 200 #number of features in hidden state
num_layers = 2 #number of stacked lstm layers

output_size = 2 #number of output classes 


In [16]:
class LSTM(nn.Module):
    def __init__(self, input_size, hidden_layer_size, output_size,num_layers):
        super().__init__()
        self.hidden_layer_size = hidden_layer_size

        self.lstm = nn.LSTM(input_size, hidden_layer_size,num_layers)

        self.linear = nn.Linear(hidden_layer_size, output_size)

        self.hidden_cell = (torch.zeros(num_layers,1,self.hidden_layer_size).to(device),
                            torch.zeros(num_layers,1,self.hidden_layer_size).to(device))

    def forward(self, input_seq):
        lstm_out, self.hidden_cell = self.lstm(input_seq.view(len(input_seq) ,1, -1), self.hidden_cell)
        predictions = self.linear(lstm_out.view(len(input_seq), -1))
        
        return predictions

In [17]:
lstm = LSTM(input_size, hidden_size,output_size,num_layers)
lstm = lstm.to(device)
lstm

LSTM(
  (lstm): LSTM(80, 200, num_layers=2)
  (linear): Linear(in_features=200, out_features=2, bias=True)
)

In [18]:
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(lstm.parameters(), lr=learning_rate)

### Training

In [19]:
epochs = 150

for i in range(epochs):
    for seq, labels in train_loader:
        lstm.train()
        seq = seq.to(device)
        labels = labels.to(device)

        

        optimizer.zero_grad()
        lstm.hidden_cell = (torch.zeros(num_layers, 1, lstm.hidden_layer_size).to(device),
                        torch.zeros(num_layers, 1, lstm.hidden_layer_size).to(device))
        
        
        y_pred = lstm(seq)
        
        #print(seq.shape)
        #print(y_pred.shape, labels.shape)
        #break

        loss = loss_function(y_pred, labels)
        loss.backward()
        optimizer.step()

    if i%10 == 0:
        print(f'epoch: {i:3} loss: {loss.item():10.8f}')

print(f'epoch: {i:3} loss: {loss.item():10.10f}')

epoch:   0 loss: 1703136.50000000
epoch:  10 loss: 30828.23437500
epoch:  20 loss: 33135.04296875
epoch:  30 loss: 20767.81445312
epoch:  40 loss: 35000.73046875
epoch:  50 loss: 31909.79687500
epoch:  60 loss: 46829.53906250
epoch:  70 loss: 14769.45312500
epoch:  80 loss: 12499.16406250
epoch:  90 loss: 9762.52929688
epoch: 100 loss: 31110.27148438
epoch: 110 loss: 33085.18750000
epoch: 120 loss: 25066.25585938
epoch: 130 loss: 31193.12109375
epoch: 140 loss: 34283.18750000
epoch: 149 loss: 24985.8652343750


In [ ]:
"""
epoch:   0 loss: 1703136.50000000
epoch:  10 loss: 30828.23437500
epoch:  20 loss: 33135.04296875
epoch:  30 loss: 20767.81445312
epoch:  40 loss: 35000.73046875
epoch:  50 loss: 31909.79687500
epoch:  60 loss: 46829.53906250
epoch:  70 loss: 14769.45312500
epoch:  80 loss: 12499.16406250
epoch:  90 loss: 9762.52929688
epoch: 100 loss: 31110.27148438
epoch: 110 loss: 33085.18750000
epoch: 120 loss: 25066.25585938
epoch: 130 loss: 31193.12109375
epoch: 140 loss: 34283.18750000
epoch: 149 loss: 24985.8652343750
"""

### Predicting

In [20]:
# need to cycle for each test set and use LSTM to predict 
# add results for each city to dataframe 
# concatinate all dataframes

def validation(model):
    cities = ["austin", "miami", "pittsburgh", "dearborn", "washington-dc","palo-alto"]

    # all the data frames
    allDF = []
    with torch.no_grad():
        for c in cities:
            
            test_dataset = ArgoverseDataset(city=c, split='test', device=device)
            test_loader = DataLoader(test_dataset,batch_size=128)

            cityPredictions = []
            for t in test_loader.dataset:
                model.eval()
                flat = torch.flatten(t)
                currentPred = []

                for i in range(60):
                    #print(flat)
                    #print(len(flat)-seqLen*2)

                    pred = torch.flatten(model(flat[len(flat)-seqLen*2:].view(1,seqLen*2)))

                    #print(flat[len(flat)-seqLen*2:].view(1,80))
                    #print(pred)

                    currentPred.append(pred)

                    #print(torch.flatten(pred).shape)
                    #print(flat.shape)
                    
                    flat = torch.cat((flat,pred),0)
                    #print(flat)

                #print(len(flat[100:]))
                cityPredictions.append(flat[100:].detach().to('cpu').numpy())
        
            df = pd.DataFrame(cityPredictions)
            df.columns = ['v' + str(i) for i in (range(120))]
            df['ID'] = [str(i) + '_' + c for i in (range(len(test_loader.dataset)))]
            allDF.append(df)
            
    return allDF


In [21]:
tempValDF = validation(lstm)


In [22]:
len(tempValDF)

6

In [23]:
lstmPredFinal = pd.concat(tempValDF)
lstmPredFinal.ID

0             0_austin
1             1_austin
2             2_austin
3             3_austin
4             4_austin
             ...      
1681    1681_palo-alto
1682    1682_palo-alto
1683    1683_palo-alto
1684    1684_palo-alto
1685    1685_palo-alto
Name: ID, Length: 29843, dtype: object

In [24]:
lstmPredFinal.to_csv("lstm3.csv", index=False)

In [25]:
torch.save(lstm.state_dict(), "lstm3.pt")

In [29]:
train_seq_data[0][0]

tensor([ -87.9163, -322.9986,  -88.1431, -323.0446,  -88.4229, -323.1046,
         -88.7523, -323.1785,  -89.1441, -323.2702,  -89.5648, -323.3791,
         -89.9902, -323.5018,  -90.4510, -323.6474,  -90.9286, -323.8175,
         -91.3744, -323.9922,  -91.7776, -324.1633,  -92.1688, -324.3469,
         -92.5615, -324.5505,  -92.9547, -324.7736,  -93.3449, -325.0163,
         -93.7345, -325.2782,  -94.1237, -325.5560,  -94.5112, -325.8491,
         -94.8992, -326.1587,  -95.2867, -326.4835,  -95.6759, -326.8234,
         -96.0662, -327.1759,  -96.4612, -327.5439,  -96.8337, -327.9260,
         -97.1968, -328.3221,  -97.5762, -328.7369,  -97.9351, -329.1604,
         -98.2598, -329.5797,  -98.5809, -330.0077,  -98.9108, -330.4610,
         -99.2353, -330.9353,  -99.5548, -331.4230,  -99.8644, -331.9220,
        -100.1664, -332.4342, -100.4591, -332.9608, -100.7423, -333.5009,
        -101.0202, -334.0549, -101.2939, -334.6228, -101.5649, -335.2033,
        -101.8345, -335.7963], device=

In [30]:
lstm(train_seq_data[0][0].view(1,80))

tensor([[-177.6523, -462.2856]], device='cuda:0', grad_fn=<AddmmBackward>)

In [ ]:
# still way off

In [32]:
modelLoad = LSTM(input_size, hidden_size, output_size, num_layers)
modelLoad.load_state_dict(torch.load("lstm3.pt"))
modelLoad.eval()


LSTM(
  (lstm): LSTM(80, 200, num_layers=2)
  (linear): Linear(in_features=200, out_features=2, bias=True)
)

In [34]:
modelLoad.to(device)

LSTM(
  (lstm): LSTM(80, 200, num_layers=2)
  (linear): Linear(in_features=200, out_features=2, bias=True)
)

In [70]:

modelLoad(train_seq_data[0][0].view(1,80))

tensor([[ -29.4129, -270.3275]], device='cuda:0', grad_fn=<AddmmBackward>)